function [lv_sol] = f_funbis(lv_n0,lv_n1,lv_n2,lv_n3,lv_n4,lv_freq,c_c,v_d1,v_d2,v_d3,v_Eref,v_Emod)

lv_sol = f_trans(lv_n0,lv_n1).*f_propagation(lv_n1,lv_freq,c_c,v_d1).*f_trans(lv_n1,lv_n2).*f_propagation(lv_n2,lv_freq,c_c,v_d2).*f_FP(lv_n0,lv_n1,lv_n2,lv_freq,c_c,v_d1).*...
        f_trans(lv_n2,lv_n3).*f_propagation(lv_n3,lv_freq,c_c,v_d3).*f_FP(lv_n1,lv_n2,lv_n3,lv_freq,c_c,v_d2).*f_trans(lv_n3,lv_n4)*f_propagation(lv_n4,lv_freq,c_c,v_d4).*...
        f_FP(lv_n2,lv_n3,lv_n4,lv_freq,c_c,v_d3) - v_Emod/v_Eref;